import sqlite3
from datetime import datetime
from utils import get_valid_input, validate_name, validate_district, validate_skills, validate_experience, validate_languages
from database import get_user_by_id, update_user_portfolio, delete_user_portfolio

def register_portfolio():
    print("\n=== Register Your Portfolio ===")

    name = get_valid_input("Full Name: ", validate_name, "")
    if not name:
        return
    
    district = get_valid_input("District: ", validate_district, "")
    if not district:
        return
    
    skills = get_valid_input("Skills (comma separated): ", validate_skills, "")
    if not skills:
        return
    
    experience = get_valid_input("Experience: ", validate_experience, "")
    if not experience:
        return
    
    languages = get_valid_input("Languages (comma separated): ", validate_languages, "")
    if not languages:
        return

    try:
        conn = sqlite3.connect("kura.db")
        cursor = conn.cursor()

        cursor.execute(
            """
        INSERT INTO users (name, district, skills, experience, languages)
        VALUES (?, ?, ?, ?, ?)
        """,
            (name, district, skills, experience, languages),
        )

        user_id = cursor.lastrowid
        conn.commit()
        conn.close()

        print(f"\n✓ Portfolio registered successfully! Your ID: {user_id}")
        print("\n--- Portfolio Summary ---")
        print(f"Name: {name}")
        print(f"District: {district}")
        print(f"Skills: {skills}")
        print(f"Experience: {experience}")
        print(f"Languages: {languages}")

        try:
            export = input("\nExport as .txt file? (y/n): ").lower()
            if export == "y":
                export_resume(user_id, name, district, skills, experience, languages)
        except KeyboardInterrupt:
            print("\nExport skipped.")
        except EOFError:
            print("\nExport skipped.")

    except Exception as e:
        print(f"Error: {e}")

def export_resume(user_id, name, district, skills, experience, languages):
    filename = f"resume_{name.replace(' ', '_')}_{user_id}.txt"

    try:
        with open(filename, "w") as f:
            f.write(f"RESUME - {name}\n")
            f.write("=" * 50 + "\n\n")
            f.write(f"ID: {user_id}\n")
            f.write(f"Name: {name}\n")
            f.write(f"District: {district}\n")
            f.write(f"Skills: {skills}\n")
            f.write(f"Experience: {experience}\n")
            f.write(f"Languages: {languages}\n")
            f.write(f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"\nGenerated by KURA - Youth Growth & Opportunity Bridge\n")

        print(f"✓ Resume exported as {filename}")
    except Exception as e:
        print(f"Error exporting resume: {e}")

def explore_opportunities():
    print("\n=== Explore Opportunities ===")

    try:
        district = input("Enter your district (or press Enter for all): ")
    except KeyboardInterrupt:
        print("\nSearch cancelled. Returning to main menu.")
        return
    except EOFError:
        print("\nNo input detected. Showing all opportunities.")
        district = ""

    try:
        conn = sqlite3.connect("kura.db")
        cursor = conn.cursor()

        if district:
            cursor.execute(
                """
            SELECT title, type, description, contact FROM opportunities 
            WHERE district LIKE ? ORDER BY created_at DESC
            """,
                (f"%{district}%",),
            )
        else:
            cursor.execute(
                """
            SELECT title, type, description, contact FROM opportunities 
            ORDER BY created_at DESC
            """
            )

        opportunities = cursor.fetchall()
        conn.close()

        if opportunities:
            print(f"\n--- Found {len(opportunities)} opportunities ---")
            for i, (title, type, description, contact) in enumerate(opportunities, 1):
                print(f"\n{i}. {title}")
                print(f"   Type: {type}")
                print(f"   Description: {description}")
                print(f"   Contact: {contact}")
        else:
            print("No opportunities found in your district.")

    except Exception as e:
        print(f"Error: {e}")

def view_portfolio():
    print("\n=== View Your Portfolio ===")
    
    try:
        user_id = input("Enter your User ID: ").strip()
        if not user_id or not user_id.isdigit():
            print("Invalid User ID. Please enter a number.")
            return
        
        user = get_user_by_id(int(user_id))
        if user:
            user_id, name, district, skills, experience, languages, created_at = user
            print("\n--- Your Portfolio ---")
            print(f"ID: {user_id}")
            print(f"Name: {name}")
            print(f"District: {district}")
            print(f"Skills: {skills}")
            print(f"Experience: {experience}")
            print(f"Languages: {languages}")
            print(f"Registered: {created_at}")
        else:
            print("No portfolio found with that ID.")
    except Exception as e:
        print(f"Error: {e}")

def update_portfolio():
    print("\n=== Update Your Portfolio ===")
    
    try:
        user_id = input("Enter your User ID: ").strip()
        if not user_id or not user_id.isdigit():
            print("Invalid User ID. Please enter a number.")
            return
        
        user = get_user_by_id(int(user_id))
        if not user:
            print("No portfolio found with that ID.")
            return
        
        print("\n--- Current Portfolio ---")
        user_id, name, district, skills, experience, languages, created_at = user
        print(f"Name: {name}")
        print(f"District: {district}")
        print(f"Skills: {skills}")
        print(f"Experience: {experience}")
        print(f"Languages: {languages}")
        
        print("\n--- Enter New Details ---")
        new_name = get_valid_input("Full Name: ", validate_name, "")
        if not new_name:
            return
        
        new_district = get_valid_input("District: ", validate_district, "")
        if not new_district:
            return
        
        new_skills = get_valid_input("Skills (comma separated): ", validate_skills, "")
        if not new_skills:
            return
        
        new_experience = get_valid_input("Experience: ", validate_experience, "")
        if not new_experience:
            return
        
        new_languages = get_valid_input("Languages (comma separated): ", validate_languages, "")
        if not new_languages:
            return
        
        if update_user_portfolio(int(user_id), new_name, new_district, new_skills, new_experience, new_languages):
            print("✓ Portfolio updated successfully!")
        else:
            print("Failed to update portfolio.")
            
    except Exception as e:
        print(f"Error: {e}")

def delete_portfolio():
    print("\n=== Delete Your Portfolio ===")
    
    try:
        user_id = input("Enter your User ID: ").strip()
        if not user_id or not user_id.isdigit():
            print("Invalid User ID. Please enter a number.")
            return
        
        user = get_user_by_id(int(user_id))
        if not user:
            print("No portfolio found with that ID.")
            return
        
        print("\n--- Portfolio to Delete ---")
        user_id, name, district, skills, experience, languages, created_at = user
        print(f"Name: {name}")
        print(f"District: {district}")
        print(f"Skills: {skills}")
        
        confirm = input("\nAre you sure you want to delete this portfolio? (y/n): ").lower()
        if confirm == 'y':
            if delete_user_portfolio(int(user_id)):
                print("✓ Portfolio deleted successfully!")
            else:
                print("Failed to delete portfolio.")
        else:
            print("Deletion cancelled.")
            
    except Exception as e:
        print(f"Error: {e}")

def portfolio_menu():
    while True:
        print("\n=== Portfolio Management ===")
        print("1. View Portfolio")
        print("2. Update Portfolio")
        print("3. Delete Portfolio")
        print("4. Back to Main Menu")
        
        try:
            choice = input("Enter your choice (1-4): ")
            if choice == "1":
                view_portfolio()
            elif choice == "2":
                update_portfolio()
            elif choice == "3":
                delete_portfolio()
            elif choice == "4":
                break
            else:
                print("Invalid choice! Please enter 1-4.")
            
            if choice != "4":
                input("\nPress Enter to continue...")
        except KeyboardInterrupt:
            print("\nReturning to main menu...")
            break
        except EOFError:
            print("\nReturning to main menu...")
            break
    def mental_health_resources():
    print("\n=== Mental Health & Wellbeing Resources ===")

    try:
        district = input("Enter your district (or press Enter for all): ")
    except KeyboardInterrupt:
        print("\nSearch cancelled. Returning to main menu.")
        return
    except EOFError:
        print("\nNo input detected. Showing all resources.")
        district = ""

    try:
        conn = sqlite3.connect("kura.db")
        cursor = conn.cursor()

        if district:
            cursor.execute(
                """
            SELECT name, type, contact, hours FROM mental_health 
            WHERE district LIKE ? ORDER BY name
            """,
                (f"%{district}%",),
            )
        else:
            cursor.execute(
                """
            SELECT name, type, contact, hours FROM mental_health 
            ORDER BY name
            """
            )

        resources = cursor.fetchall()
        conn.close()

        if resources:
            print(f"\n--- Found {len(resources)} resources ---")
            for i, (name, type, contact, hours) in enumerate(resources, 1):
                print(f"\n{i}. {name}")
                print(f"   Type: {type}")
                print(f"   Contact: {contact}")
                print(f"   Hours: {hours}")
        else:
            print("No mental health resources found in your district.")

    except Exception as e:
        print(f"Error: {e}")

    try:
        conn = sqlite3.connect("kura.db")
        cursor = conn.cursor()

        if district:
            cursor.execute(
                """
            SELECT name, type, contact, hours FROM mental_health 
            WHERE district LIKE ? ORDER BY name
            """,
                (f"%{district}%",),
            )
        else:
            cursor.execute(
                """
            SELECT name, type, contact, hours FROM mental_health 
            ORDER BY name
            """
            )

        resources = cursor.fetchall()
        conn.close()

        if resources:
            print(f"\n--- Found {len(resources)} resources ---")
            for i, (name, type, contact, hours) in enumerate(resources, 1):
                print(f"\n{i}. {name}")
                print(f"   Type: {type}")
                print(f"   Contact: {contact}")
                print(f"   Hours: {hours}")
        else:
            print("No mental health resources found in your district.")

    except Exception as e:
        print(f"Error: {e}")
